public with sharing class IPUE_CONSTANTS {


    public static final String ESTIMATION_SCHEDULE_DEV_NAME = 'Estimation_Schedule';

    /**** Estimation Schedule Data Types ****/
    public static final String TABLE_FIXED = 'Table - Fixed';
    public static final String TABLE_ELASTIC = 'Table - Elastic';
    public static final String STATIC_TEXT = 'Static Text';
    public static final String CALCULATED = 'Calculated';
    public static final String TEXT = 'Text';
    public static final String NUM = 'Number';
    public static final String PICKLIST = 'Picklist';

    /****** Keys Used in CalculationUtils ********/
    public static final String DEFAULT_KEY = 'Default';
    public static final String ROW_KEY = '_ROW_';
    public static final String COLUMN_KEY = '_COLUMN_';
    
    //Added empty constructor to get code coverage
    public IPUE_CONSTANTS(){}

}