/**************************************************************************
JS file Name: InfaKBInternalSearchTemplate.js.
Author: Sathish Rajalingam
Company: Informatica
Date: 24-April-2021
Purpose: Holds all the template for the internal search.
Version: 1.0

Modificaiton History

Date       |  Modified by    |  Jira reference      |       ChangesMade               |     Tag
        
***************************************************************************/
Coveo.TemplateCache.registerTemplate("SalesforceCase", Coveo.HtmlTemplate.fromString(document.querySelector(".SalesforceCase").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"), { "condition": null, "layout": "list", "fieldsToMatch": [{ "field": "sfcaseid" }, { "field": "sfcasenumber" }], "mobile": null, "role": null }), true, true); document.querySelector(".SalesforceCase").outerHTML = "";
Coveo.TemplateCache.registerTemplate("Chatter", Coveo.HtmlTemplate.fromString(document.querySelector(".Chatter").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"),{"condition": null, "layout": "list", "fieldsToMatch": [{ "field": "objecttype", "values": ["FeedItem", "FeedComment"] }], "mobile": null, "role": null}),true, true); document.querySelector(".Chatter").outerHTML = "";
Coveo.TemplateCache.registerTemplate("LearningPath", Coveo.HtmlTemplate.fromString(document.querySelector(".LearningPath").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"),{"condition": null, "layout": "list", "fieldsToMatch": [{ "field": "infacontenttype", "values": ["Learning Paths"] }], "mobile": null, "role": null}),true, true); document.querySelector(".LearningPath").outerHTML = "";
Coveo.TemplateCache.registerTemplate("Expert", Coveo.HtmlTemplate.fromString(document.querySelector(".Expert").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"),{"condition": null, "layout": "list", "fieldsToMatch": [{ "field": "infacontenttype", "values": ["Expert Assistant"] }], "mobile": null, "role": null}),true, true); document.querySelector(".Expert").outerHTML = "";
Coveo.TemplateCache.registerTemplate("Velocity", Coveo.HtmlTemplate.fromString(document.querySelector(".Velocity").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"),{"condition": null, "layout": "list", "fieldsToMatch": [{ "field": "infadocumenttype", "values": ["Velocity"] }], "mobile": null, "role": null}),true, true); document.querySelector(".Velocity").outerHTML = "";
Coveo.TemplateCache.registerTemplate("SupportVideo", Coveo.HtmlTemplate.fromString(document.querySelector(".SupportVideo").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"),{"condition": null, "layout": "list", "fieldsToMatch": [{ "field": "infadocumenttype", "values": ["SupportVideo"] }], "mobile": null, "role": null}),true, true); document.querySelector(".SupportVideo").outerHTML = "";
Coveo.TemplateCache.registerTemplate("ProdDocs", Coveo.HtmlTemplate.fromString(document.querySelector(".ProdDocs").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"),{"condition": null, "layout": "list", "fieldsToMatch": [{ "field": "infadocumenttype", "values": ["Documentation", "H2L", "PAMEOL"] }], "mobile": null, "role": null}),true, true); document.querySelector(".ProdDocs").outerHTML = "";
Coveo.TemplateCache.registerTemplate("DocPortal", Coveo.HtmlTemplate.fromString(document.querySelector(".DocPortal").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"),{"condition": null, "layout": "list", "fieldsToMatch": [{ "field": "infadocumenttype", "values": ["DocPortal"] }], "mobile": null, "role": null}),true, true); document.querySelector(".DocPortal").outerHTML = "";
Coveo.TemplateCache.registerTemplate("SalesforceKBInternal", Coveo.HtmlTemplate.fromString(document.querySelector(".SalesforceKBInternal").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"),{"condition": null, "layout": "list", "fieldsToMatch": [{ "field": "connectortype", "values": ["Salesforce2"] },{ "field": "infapermissiontype", "values": ["Internal"] }], "mobile": null, "role": null}),true, true); document.querySelector(".SalesforceKBInternal").outerHTML = "";
Coveo.TemplateCache.registerTemplate("SalesforceKBDraft", Coveo.HtmlTemplate.fromString(document.querySelector(".SalesforceKBDraft").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"),{"condition": null, "layout": "list", "fieldsToMatch": [{ "field": "connectortype", "values": ["Salesforce2"] },{ "field": "infapermissiontype", "values": ["Public"] }, { "field": "infamoderationstatus", "values": ["1", "2", "3", "4"] }], "mobile": null, "role": null}),true, true); document.querySelector(".SalesforceKBDraft").outerHTML = "";
Coveo.TemplateCache.registerTemplate("SalesforceKBPublic", Coveo.HtmlTemplate.fromString(document.querySelector(".SalesforceKBPublic").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"),{"condition": null, "layout": "list", "fieldsToMatch": [{ "field": "connectortype", "values": ["Salesforce2"] },{ "field": "infapermissiontype", "values": ["Public"] }, { "field": "infamoderationstatus", "values": ["0"] }], "mobile": null, "role": null}),true, true); document.querySelector(".SalesforceKBPublic").outerHTML = "";
Coveo.TemplateCache.registerTemplate("Jive", Coveo.HtmlTemplate.fromString(document.querySelector(".Jive").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"),{"condition": null, "layout": "list", "fieldsToMatch": [{ "field": "sourcetype", "values": ["Jive"] }],"mobile": null, "role": null}),true, true); document.querySelector(".Jive").outerHTML = "";
Coveo.TemplateCache.registerTemplate("Cases", Coveo.HtmlTemplate.fromString(document.querySelector(".Cases").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"),{"condition": null, "layout": "list", "fieldsToMatch": [{ "field": "infadocumenttype", "values": ["Cases"] }], "mobile": null, "role": null}),true, true); document.querySelector(".Cases").outerHTML = "";
Coveo.TemplateCache.registerTemplate("Bugs", Coveo.HtmlTemplate.fromString(document.querySelector(".Bugs").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"),{"condition": null, "layout": "list", "fieldsToMatch": [{ "field": "athenatabname", "values": ["Product Bugs"] }], "mobile": null, "role": null}),true, true); document.querySelector(".Bugs").outerHTML = "";
Coveo.TemplateCache.registerTemplate("Default", Coveo.HtmlTemplate.fromString(document.querySelector(".Default").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"),{"condition": null, "layout": "list", "fieldsToMatch": null, "mobile": null, "role": null}), true, true); document.querySelector(".Default").outerHTML = "";
Coveo.TemplateCache.registerTemplate("CaseComment", Coveo.HtmlTemplate.fromString(document.querySelector(".CaseComment").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"),{"condition": null, "layout": "list", "fieldsToMatch": null, "mobile": null, "role": null}), true, true); document.querySelector(".CaseComment").outerHTML = "";
Coveo.TemplateCache.registerTemplate("ProdDocsAttachment", Coveo.HtmlTemplate.fromString(document.querySelector(".ProdDocsAttachment").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"),{"condition": null, "layout": "list", "fieldsToMatch": null, "mobile": null, "role": null}), true, true); document.querySelector(".ProdDocsAttachment").outerHTML = "";
Coveo.TemplateCache.registerTemplate("ProductDocChildResult", Coveo.HtmlTemplate.fromString(document.querySelector(".ProductDocChildResult").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"),{"condition": null, "layout": "list", "fieldsToMatch": null, "mobile": null, "role": null}), true, true); document.querySelector(".ProductDocChildResult").outerHTML = "";
Coveo.TemplateCache.registerTemplate("JiveChildResult", Coveo.HtmlTemplate.fromString(document.querySelector(".JiveChildResult").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"), { "condition": null, "layout": "list", "fieldsToMatch": null, "mobile": null, "role": null }), true, true); document.querySelector(".JiveChildResult").outerHTML = "";
Coveo.TemplateCache.registerTemplate("CoveoCustomNoResults", Coveo.HtmlTemplate.fromString(document.querySelector(".CoveoCustomNoResults").innerHTML.replace("href=\"javascript:void(0);\"></a>","></a>"),{"condition": null, "layout": "list", "fieldsToMatch": null, "mobile": null, "role": null}), true, true); document.querySelector(".CoveoCustomNoResults").outerHTML = "";
